# Generated by Django 6.0.2 on 2026-02-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique conversation/context identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("agent_id", models.CharField(help_text="Agent identifier", max_length=255)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional conversation metadata",
                        null=True,
                    ),
                ),
                (
                    "is_streaming",
                    models.BooleanField(
                        default=False, help_text="Whether this conversation has an active stream"
                    ),
                ),
                (
                    "stream_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to connect to the stream",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "a2a_conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="A2ATask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique task identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Context ID for grouping related tasks",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status_state",
                    models.CharField(
                        db_index=True,
                        default="submitted",
                        help_text="Current state of the task",
                        max_length=50,
                    ),
                ),
                (
                    "status_message",
                    models.JSONField(blank=True, help_text="Status message as JSON", null=True),
                ),
                (
                    "history",
                    models.JSONField(default=list, help_text="Message history for this task"),
                ),
                (
                    "artifacts",
                    models.JSONField(
                        default=list, help_text="List of artifacts produced by the task"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional task metadata", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "a2a_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["context_id", "created_at"], name="a2a_tasks_context_a617c8_idx"
                    ),
                    models.Index(
                        fields=["status_state", "created_at"], name="a2a_tasks_status__73b567_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PushNotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "config_id",
                    models.CharField(help_text="Configuration identifier", max_length=255),
                ),
                ("url", models.URLField(help_text="Webhook URL for notifications", max_length=500)),
                (
                    "authentication",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Authentication configuration",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_configs",
                        to="a2a_app.a2atask",
                    ),
                ),
            ],
            options={
                "db_table": "a2a_push_configs",
                "unique_together": {("task", "config_id")},
            },
        ),
    ]
